name: Frontend CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Run linter and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: src/
        
      - name: Lint Action
        run: lint
